--
grails:
  plugin:
          awssdk:
              accessKey: {ACCESS_KEY} # Global default setting
              secretKey: {SECRET_KEY} # Global default setting
              region: us-east-1       # Global default setting
              s3:
                  accessKey: {ACCESS_KEY} # (optional)
                  secretKey: {SECRET_KEY} # (optional)
                  region: eu-west-1       # (optional)
                  bucket: my-bucket       # (optional)